In [1]:
import scipy as spy
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.io import loadmat
import math
import pandas as pd

In [2]:
A = np.array( [  [ 1,-1],
                 [ 2,0],
                 [ 0,1]] )

In [3]:
A_orth=spy.linalg.orth(A)

In [5]:
A_orth

array([[-0.54146663,  0.51222011],
       [-0.83125078, -0.44487192],
       [ 0.12584124, -0.73465607]])

In [6]:
1/math.sqrt(5)

0.4472135954999579

In [7]:
A_orth[:,0]

array([-0.54146663, -0.83125078,  0.12584124])

In [8]:
np.dot(A_orth[:,0],A_orth[:,1])

2.7755575615628914e-17

In [9]:
np.linalg.norm(A_orth[:,0])

0.9999999999999996

In [10]:
np.linalg.norm(A_orth[:,1])

0.9999999999999998

In [13]:
np.linalg.norm((A[:,0])*(1/math.sqrt(5)))

0.9999999999999999

In [15]:
u1=(A[:,0])*(1/math.sqrt(5))

In [16]:
u1

array([0.4472136 , 0.89442719, 0.        ])

In [22]:
temp = np.array([-4,2,5])

In [23]:
temp

array([-4,  2,  5])

In [24]:
u2 = temp*(1/(3*math.sqrt(5)))

In [25]:
u2

array([-0.59628479,  0.2981424 ,  0.74535599])

In [26]:
np.linalg.norm(u1)

0.9999999999999999

In [27]:
np.linalg.norm(u2)

1.0

In [28]:
np.dot(u1,u2)

0.0

In [37]:
M=np.array([u1,u2]).T

In [38]:
M

array([[ 0.4472136 , -0.59628479],
       [ 0.89442719,  0.2981424 ],
       [ 0.        ,  0.74535599]])

In [40]:
P=np.matmul(M,M.T)

In [52]:
P

array([[ 0.55555556,  0.22222222, -0.44444444],
       [ 0.22222222,  0.88888889,  0.22222222],
       [-0.44444444,  0.22222222,  0.55555556]])

In [41]:
x=np.array([[0],[2],[1]])

In [42]:
x

array([[0],
       [2],
       [1]])

In [43]:
proj = np.matmul(P,x)

In [44]:
proj

array([[-1.11022302e-16],
       [ 2.00000000e+00],
       [ 1.00000000e+00]])

In [49]:
x_alt=np.array([[1],[2],[1]])

In [50]:
proj_alt = np.matmul(P,x_alt)

In [51]:
proj_alt

array([[0.55555556],
       [2.22222222],
       [0.55555556]])