In [23]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from  imageio import imread
import pandas as pd
import sympy as sp
import math

In [2]:
A = np.array( [  [ -2, -1, 1],
                 [ 0, -1, 0],
                 [ -1, 1, 2],
                 [ 1, -1, 1]] )

In [3]:
A

array([[-2, -1,  1],
       [ 0, -1,  0],
       [-1,  1,  2],
       [ 1, -1,  1]])

In [4]:
A.shape

(4, 3)

In [15]:
At_A=np.matmul(A.T,A)

In [17]:
At_A

array([[ 6,  0, -3],
       [ 0,  4,  0],
       [-3,  0,  6]])

In [18]:
At_A_4 = np.array([[ 2,  0, -3],
       [ 0,  0,  0],
       [-3,  0,  2]])

In [20]:
sp.Matrix(At_A_4).rref()

(Matrix([
 [1, 0, 0],
 [0, 0, 1],
 [0, 0, 0]]), (0, 2))

In [35]:
At_A_9 = np.array([[ -3,  0, -3],
       [ 0,  -5,  0],
       [-3,  0,  -3]])

In [36]:
sp.Matrix(At_A_9).rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 0],
 [0, 0, 0]]), (0, 1))

In [37]:
At_A_3 = np.array([[ 3,  0, -3],
       [ 0,  1,  0],
       [-3,  0,  3]])

In [38]:
sp.Matrix(At_A_3).rref()

(Matrix([
 [1, 0, -1],
 [0, 1,  0],
 [0, 0,  0]]), (0, 1))

##### null space of $A^T$

In [39]:
sp.Matrix(A.T).rref()

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  3],
 [0, 0, 1,  1]]), (0, 1, 2))

In [40]:
1/(2*math.sqrt(3))

0.2886751345948129

In [5]:
U,S,V=np.linalg.svd(A)

In [12]:
U.shape,S.shape,V.shape

((4, 4), (3,), (3, 3))

In [9]:
pd.DataFrame(U)

0    1         2         3
0 -7.071068e-01 -0.5  0.408248  0.288675
1  0.000000e+00 -0.5  0.000000 -0.866025
2 -7.071068e-01  0.5 -0.408248 -0.288675
3 -2.125204e-16 -0.5 -0.816497  0.288675

In [10]:
pd.DataFrame(S)

0
0  3.000000
1  2.000000
2  1.732051

In [11]:
pd.DataFrame(V)

0    1         2
0  0.707107  0.0 -0.707107
1  0.000000  1.0  0.000000
2 -0.707107  0.0 -0.707107

In [24]:
1/math.sqrt(2)

0.7071067811865475

In [46]:
rank_k=[1,2,3]

i=0
for k in rank_k:
    A_k = np.dot(U[:,:k],np.dot(np.diag(S[:k]),V[:k,:]))
    print("Rank "+str(k)+" matrix\n")
    print(A_k.shape)
    print(pd.DataFrame(A_k))
    print("\n")

Rank 1 matrix

(4, 3)
              0    1             2
0 -1.500000e+00 -0.0  1.500000e+00
1  0.000000e+00  0.0 -0.000000e+00
2 -1.500000e+00 -0.0  1.500000e+00
3 -4.508238e-16 -0.0  4.508238e-16


Rank 2 matrix

(4, 3)
              0    1             2
0 -1.500000e+00 -1.0  1.500000e+00
1  0.000000e+00 -1.0  0.000000e+00
2 -1.500000e+00  1.0  1.500000e+00
3 -4.508238e-16 -1.0  4.508238e-16


Rank 3 matrix

(4, 3)
     0    1    2
0 -2.0 -1.0  1.0
1  0.0 -1.0  0.0
2 -1.0  1.0  2.0
3  1.0 -1.0  1.0




In [53]:
U[:,:3]

array([[-7.07106781e-01, -5.00000000e-01,  4.08248290e-01],
       [ 0.00000000e+00, -5.00000000e-01,  0.00000000e+00],
       [-7.07106781e-01,  5.00000000e-01, -4.08248290e-01],
       [-2.12520397e-16, -5.00000000e-01, -8.16496581e-01]])

In [54]:
np.diag(S[:3])

array([[3.        , 0.        , 0.        ],
       [0.        , 2.        , 0.        ],
       [0.        , 0.        , 1.73205081]])

In [55]:
V[:3,:]

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [-0.70710678,  0.        , -0.70710678]])

In [47]:
A.shape

(4, 3)

In [48]:
pd.DataFrame(U)

0    1         2         3
0 -7.071068e-01 -0.5  0.408248  0.288675
1  0.000000e+00 -0.5  0.000000 -0.866025
2 -7.071068e-01  0.5 -0.408248 -0.288675
3 -2.125204e-16 -0.5 -0.816497  0.288675